on: workflow_dispatch
name: 🚀 Deploy website on click
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"

      - name: 🔨 Build Project
        run: |
          npm i
          touch .env.local
            echo NEXT_PUBLIC_SMTP_SENDER=${{ secrets.NEXT_PUBLIC_SMTP_SENDER }} >> .env.local
            echo NEXT_PUBLIC_SMTP_RECEIVER=${{ secrets.NEXT_PUBLIC_SMTP_RECEIVER }} >> .env.local
            echo NEXT_PUBLIC_SMTP_PASS=${{ secrets.NEXT_PUBLIC_SMTP_PASS }} >> .env.local
            echo NEXT_PUBLIC_STRAPI_API_URL=${{ secrets.NEXT_PUBLIC_STRAPI_API_URL }} >> .env.local
            echo NEXT_PUBLIC_API_TOKEN=${{ secrets.NEXT_PUBLIC_API_TOKEN }} >> .env.local
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: bat-max.atthost24.pl
          username: bat-max_przemek
          password: ${{ secrets.PASSWORD }}
          server-dir: websites/frontend/
